# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-05 09:15
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=150)),
                ('slug', models.SlugField(max_length=150, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=50)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('item_picture', models.ImageField(upload_to='profile')),
                ('expiry_date', models.DateTimeField()),
                ('available', models.BooleanField(default=True)),
                ('stock', models.PositiveIntegerField()),
                ('original_price', models.IntegerField()),
                ('today_price', models.IntegerField()),
            ],
            options={
                'ordering': ('upload_date',),
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('business_logo', models.ImageField(blank=True, upload_to='profile/')),
                ('business_description', tinymce.models.HTMLField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=100)),
                ('business_identification_number', models.CharField(max_length=100)),
                ('prefered_username', models.CharField(max_length=100)),
                ('business_phone_number', models.IntegerField()),
                ('business_email', models.EmailField(max_length=254)),
                ('Business_address', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterIndexTogether(
            name='item',
            index_together=set([('id', 'profile')]),
        ),
    ]
