# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-08 09:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instaclone', '0002_item_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='expiry_date',
            field=models.DateTimeField(null=True),
        ),
    ]
