# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-03 10:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instaclone', '0002_auto_20190702_1220'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Buyer',
        ),
        migrations.AddField(
            model_name='item',
            name='available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='item',
            name='stock',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
