# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-08 09:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instaclone', '0003_auto_20190708_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='original_price',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='stock',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='today_price',
            field=models.IntegerField(null=True),
        ),
    ]
