# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-03 11:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_delete_assumpta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buyer',
            name='last_name',
        ),
    ]
