# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-03 11:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_remove_buyer_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyer',
            name='last_name',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
    ]
